test: test.cpp PoligonoIrreg.o
	g++ test.cpp PoligonoIrreg.o Coordenada.o -o test
test: test.cpp PoligonoIrreg.
	g++ test.cpp PoligonoIrreg.o Coordenada.o -o test
PoligonoIrreg.o: PoligonoIrreg.cpp Coordenada.o PoligonoIrreg.h
	g++ PoligonoIrreg.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c
